### PR TITLE
fix: improve keyboard shortcuts

### LINKED ISSUE #5492: [bug]: Keyboard Shortcut Improvements (Undo/Redo, Comment/Uncomment)
### Is there an existing issue for this?

- [x] I have searched existing issues and this bug hasn't been reported yet

### Platform

Web App

### Browser

Chrome

### Operating System

Windows

### Bug Description

**Current Behavior:**
Certain keyboard shortcuts are not functioning as expected in Hoppscotch:

Cmd+/: Instead of toggling comments in the editors, it opens the shortcuts panel.
Cmd+Z / Cmd+Y: Undo and Redo functions are inconsistent across editors.
No option to close tabs using any shortcut in web app.

**Steps to Reproduce:**
Open any editor in Hoppscotch (e.g., request body, variables, headers, scripting tabs).
Press Cmd+/ to toggle comments (not working, instead it opens the shortcuts panel).
Perform actions and try Cmd+Z / Cmd+Y to Undo/Redo (not working as expected).

https://github.com/user-attachments/assets/97dcd800-b961-4454-8cfa-37a4267d6961

### Deployment Type

Hoppscotch Cloud

### Version

2025.9.2

### PR DESCRIPTION
**Pull request by chhaviG22**
Closes #5492
#5592 

This PR addresses improvements to keyboard shortcuts, enhancing the user experience across editors and fixing previous inconsistencies.

### What's changed
**Cmd+/**: Now toggles comments in editors on focus and otherwise opens the side panel
**Cmd+Z / Cmd+Y**: Fixed undo/redo functionality across all editors.
**Cmd+W**: Closes tabs in the desktop app.
**Cmd+D**: Closes tabs in the web app.
Added all keyboard shortcut definitions to the shortcuts side panel for better visibility and user guidance.

---
## Summary by cubic
Improves keyboard shortcuts across editors and platforms. Cmd+/ now toggles comments, Cmd+Shift+/ opens the shortcuts panel, and Cmd+Z/Cmd+Y undo/redo work consistently. Addresses #5492.

- **New Features**
  - Web: Cmd+D closes the current tab. Desktop: Cmd+W closes tabs.
  - Shortcuts panel updated to show Undo, Redo, Comment/Uncomment, and platform-specific Close Tab.

- **Bug Fixes**
  - Comment toggle works in CodeMirror and Monaco; JSONC now supports line comments.
  - Undo/Redo fixed across editors (adds Cmd+Y redo in Monaco and CodeMirror keymap).
  - Keybinding handling updated to avoid browser conflicts, let editors handle undo/redo/comment when focused, and ensure Cmd+/ closes the shortcuts panel even when the search input is focused.

<sup>Written for commit 0907327f2be46653288c31b4d580c9de649d074e. Summary will update automatically on new commits.</sup>

### CODE REVIEW

File: packages/hoppscotch-common/src/helpers/keybindings.ts [hunk 1]
```diff
@@ -154,6 +173,48 @@ function handleKeyDown(ev: KeyboardEvent) {
...
+      (isCodeMirrorEditor(target) || isMonacoEditor(target))
+    ) {
+      return
+    }
+    // If not in editor, fall back to keybinds flyout if no other action is bound
+    if (!boundAction) {
+      invokeAction("flyouts.keybinds.toggle", undefined, "keypress")
+      ev.preventDefault()
+      return
+    }
```
Comment (nivedin) [inline packages/hoppscotch-common/src/helpers/keybindings.ts]: When an input is not focused, we can fall back to the cmd+/ shortcut to open the shortcut flyout, and we can keep the cmd+/ shortcut unchanged.

File: packages/hoppscotch-common/src/components/app/Footer.vue [hunk 2]
```diff
@@ -146,7 +146,7 @@
           v-tippy="{ theme: 'tooltip', allowHTML: true }"
           :title="`${t(
             'app.shortcuts'
-          )} <kbd>${getSpecialKey()}</kbd><kbd>/</kbd>`"
```
Comment (nivedin) [inline packages/hoppscotch-common/src/components/app/Footer.vue:149]: we can revert this to 'cmd+/'

**Review by nivedin — CHANGES_REQUESTED** [review]

File: packages/hoppscotch-common/src/components/app/Footer.vue (hunk 2 above)
Comment (chhaviG22) [reply packages/hoppscotch-common/src/components/app/Footer.vue:149]: @nivedin Changed shortcuts panel keybinding display from `Cmd+Shift+/` to `Cmd+/`
Cmd+/ now intelligently adapts based on where you press it:
- In code editors → Toggles comments
- On the page (not typing) → Opens shortcuts panel
- In normal input fields → Types / character

**Review by nivedin — APPROVED** [review]
LGTM 💯

File: packages/hoppscotch-common/src/helpers/shortcuts.ts [hunk 3]
```diff
@@ -33,6 +33,21 @@ export function getShortcuts(t: (x: string) => string): ShortcutDef[] {
...
+      section: t("shortcut.general.title"),
+    },
+    {
+      label: t("shortcut.general.redo"),
+      keys: [getPlatformSpecialKey(), "Y"],
+      section: t("shortcut.general.title"),
+    },
+    {
+      label: t("shortcut.general.comment_uncomment"),
+      keys: [getPlatformSpecialKey(), "/"],
```
[the remark this answers is not in the document]
Comment (nivedin) [reply packages/hoppscotch-common/src/helpers/shortcuts.ts:48]: Please edit the PR description @chhaviG22

**Comment by nivedin** [comment]
Please rebase the branch to the upstream
