### PR TITLE
💚 Fixed #497

### LINKED ISSUE #497: GraphQL String variables are null
**Describe the bug**
String variables provided for GraphQL query have null values.
Besides unquoted input I also tried to wrap String variable value with double and single quotes but result was the same.

**To Reproduce**
1. Go to /graphql
2. Provide GraphQL query
3. Provide variables (including String type variable)
4. Click "Run Query"
5. See null variables values in request preview in console

**Screenshots**
Screen Shot 2020-01-17 at 11 10 41
Screen Shot 2020-01-17 at 11 11 22

**Desktop**
 - OS: macOS
 - Browser: chrome
 - Version 79.0.3945.88 (Official Build) (64-bit)

**Additional context**
Query performed with proxy disabled in settings

### PR DESCRIPTION
**Pull request by pushrbx**
This fixes the issue with null string type variables, as described in #497

### CODE REVIEW

File: pages/graphql.vue [hunk 1]
```diff
@@ -667,16 +667,12 @@ export default {
...
-          floatRex.compile();
-
-          if (intRex.test(gqlQueryString)) {
+          if (gqlQueryString.indexOf(`\$${variable.key}: Int`) > -1) {
             variables[variable.key] = parseInt(variable.value);
-          } else if (floatRex.test(gqlQueryString)) {
+          } else if (gqlQueryString.indexOf(`\$${variable.key}: Float`) > -1) {
             variables[variable.key] = parseFloat(variable.value);
           } else {
+            console.log(variable);
```
Comment (liyasthomas) [inline pages/graphql.vue]: please remove `console.log()`

Comment (pushrbx) [reply pages/graphql.vue]: done
