### PR TITLE
fix(relay): multiple Set-Cookie headers in resp

### LINKED ISSUE #1546: Cookie missing in response
The response has three set-cookies,But it only gets one(Please forgive me for my poor English)

### LINKED ISSUE #5344: [bug]: hoppscotch is ignoring one set-cookie when response has 2 values
### Is there an existing issue for this?

- [x] I have searched existing issues and this bug hasn't been reported yet

### Platform

Desktop App

### Browser

Edge

### Operating System

Windows

### Bug Description

When a request sends two ‘set-cookie’ in response headers(postman displays it as 2 separate headers and Bruno displays it as one array of ‘set-cookie’ of comma separated value), hoppscotch is ignoring one of them.

Because of this, we need to make 2 calls to get both cookies. Get first cookie on request-1 and set it to send request-2, then I will get the second cookie. This was one call in both postman and Bruno. Also cookie update in hoppscotch is painfully manual so more time consuming, atleast in desktop.

### Deployment Type

Self-hosted (on-prem deployment)

### Version

v2025.7.1

### LINKED ISSUE #5375: [bug]: Response header only shows first Set-Cookie when multiple cookies are present
### Is there an existing issue for this?

- [x] I have searched existing issues and this bug hasn't been reported yet

### Platform

Desktop App

### Browser

Safari

### Operating System

macOS

### Bug Description

When the server response contains two or more Set-Cookie headers, Hoppscotch only displays the first one. This makes it impossible to debug APIs that rely on multiple cookies being set in a single response.

**Steps to Reproduce:**
	1.	Send a request to an endpoint that returns multiple Set-Cookie headers.
	2.	Check the response headers panel in Hoppscotch.
	3.	Only the first Set-Cookie is shown.

**Expected Behavior:**
All Set-Cookie headers should be displayed, not just the first one.

**Additional context:**
This is important for working with frameworks like Laravel, where both XSRF-TOKEN and laravel_session cookies are usually returned together.

### Deployment Type

Self-hosted (on-prem deployment)

### Version

25.8.1 - Desktop Application

### PR DESCRIPTION
**Pull request by CuriousCorrelation**
This is an experimental way to fix multiple `Set-Cookie` headers being
 lost during HTTP response pre/post-processing by concat-ing them with
 `\n` in the networking layer, so all cookies to be displayed in the
 response headers panel instead of only the first one being visible.
 
 | Before | After |
 | --- | --- |
 | image |  image |

 NOTE: This is an experimental workaround for the time being.
 `\n` is used here as a separator because HTTP headers are inherently
 line-oriented (`\r\n` on the wire). This makes it trivial to split back
 into distinct `Set-Cookie` headers without violating RFC rules. The
 next idea would be using a custom delimiter but it also would be
 arbitrary and risk breaking if that delimiter ever appeared in a cookie
 value.  The main trade-off is that this is a fragile workaround,
 unusual edge cases (e.g. malformed cookies containing newlines, or
 components that normalize headers differently) may fail. A full fix
 would require changing the header storage structure to support multiple
 values per key (the rough idea around that is explained in FE-1008).

 Closes FE-1008 (phase-1)
 Closes FE-309
 Closes #1546 (multiple Set-Cookie headers missing in response display)
 Closes #5344 (ignoring one Set-Cookie when response has 2 values)
 Closes #5375 (only shows first Set-Cookie when multiple cookies present)
 Partially addresses #3532 (fixes header display, automatic cookie
 storage will be handled separately).

 When servers returned multiple `Set-Cookie` headers, only the first
 header was preserved while subsequent ones were discarded.

 The issue occurres because `HashMap<String, String>` data structure in
 `TransferHandler` could only store one value per header name (by the
 very nature of hashmaps or records for instance).

 ### What's changed

 #### Relay networking layer

 The header processing in `transfer.rs` now includes special handling
 just for `set-cookie` headers (case-insensitive accumulator). When
 multiple Set-Cookie headers are encountered, they are concatenated with
 newlines (why is explained above).

 #### FE processing

 Added `processHeaders` function in `response.ts` that
 splits concatenated `Set-Cookie` headers back into separate header
 entries.

 #### Dependencies

 Updated `relay` and `tauri-plugin-relay` to commits that include the
 `Set-Cookie` concatenation fix across all target packages.

 ### Testing

 Test with any endpoints that set multiple cookies:

 ```bash
 curl -i http://localhost:3000/multiple-cookies
 ```

 or perhaps use `httpbin`:

 ```bash
 curl -i -G \
 --data-urlencode "Set-Cookie=sessionid=abc123; Path=/" \
 --data-urlencode "Set-Cookie=csrftoken=xyz789; Path=/" \
 --data-urlencode "Set-Cookie=userid=user456; Path=/" \
 "https://httpbin.org/response-headers"
 ```

 or even a custom server script:

 ```javascript
 const http = require('http');

 const server = http.createServer((req, res) => {
   if (req.url === '/multiple-cookies') {
     res.setHeader('Set-Cookie', [
       'sessionid=abc123; Path=/',
       'csrftoken=xyz789; Path=/',
       'userid=user456; Path=/'
     ]);
     res.setHeader('Content-Type', 'application/json');
     res.end(JSON.stringify({ message: 'Multiple cookies set' }));
   }
 });
 ```

 #### Expected response headers:

 ```
 Set-Cookie: sessionid=abc123; Path=/
 Set-Cookie: csrftoken=xyz789; Path=/
 Set-Cookie: userid=user456; Path=/
 ```

 In desktop app response headers panel, all three cookies now appear as
 separate header entries **instead of only the first one** being
 visible.

 ### Special Note On Backwards Compat

 This preserves the existing `HashMap<String, String>` structure without
 requiring changes to the `RelayResponse` interface or frontend header
 processing pipeline since this will have a rather large ripple effect
 all over the codebase. A complete fix is described in FE-1008.

 ### Implementation notes

 The comment in `processHeaders` should explain the rationale:

 > A complete solution would involve swapping `Record`/`HashMap` with a
 > flat array and propagating the refactor throughout the codebase, from
 > the underlying networking to the frontend. The problem with that
 > approach is you lose that O(1) lookup. A simpler approach is
 > `HashMap<String, Vec<String>>` but even that doesn't substantially
 > reduce the refactor surface area.

 The newline concatenation also preserves O(1) header lookup
 performance.

### CODE REVIEW

File: packages/hoppscotch-common/src/helpers/kernel/rest/response.ts [hunk 1]
```diff
@@ -21,6 +21,39 @@ const extractTiming = (response: RelayResponse): number =>
...
+// also little point in going from key-value to key-pair-value since
+// you'd just be putting this same workaround somewhere else.
+// A simpler approach is `HashMap<String, Vec<String>>` but even that
+// doesn't substantially reduces the refactor surface area.
+// Given all of those issues, a temporary workaround is perhaps the best
+// solution at the moment.
+const processHeaders = (headers: Record<string, string>): HoppRESTResponseHeader[] => {
+  const processedHeaders: HoppRESTResponseHeader[] = []
+
+  for (const [key, value] of Object.entries(headers ?? {})) {
```
Comment (jamesgeorge007) [inline packages/hoppscotch-common/src/helpers/kernel/rest/response.ts:53]: Can we ensure the type contracts and implementation align such that `headers` being falsy is indicated in the types?

File: packages/hoppscotch-common/src/helpers/kernel/rest/response.ts [hunk 2]
```diff
@@ -21,6 +21,39 @@ const extractTiming = (response: RelayResponse): number =>
...
+    if (key.toLowerCase() === 'set-cookie') {
+      // To split concatenated `Set-Cookie` headers and create separate header entries,
+      // see `if key.to_lowercase() == "set-cookie" {` in `transfer.rs`
+      const cookieStrings = value.split('\n').map(s => s.trim()).filter(s => s)
```
Comment (jamesgeorge007) [inline packages/hoppscotch-common/src/helpers/kernel/rest/response.ts]:
```suggestion
      const cookieStrings = value.split('\n').map(s => s.trim()).filter(Boolean)
```

Subjective, in case you prefer the idiomatic style.

File: packages/hoppscotch-common/src/helpers/kernel/rest/response.ts (hunk 1 above)
Comment (CuriousCorrelation) [reply packages/hoppscotch-common/src/helpers/kernel/rest/response.ts:53]: While I don’t quite remember why this defensive pattern was added (perhaps something to do with proxy stripping headers with agent), I traced it from the kernel to interceptors to the presentation layer and headers do seem to be always preserved. Although I’d err on the side of caution and keep it there, so I have changed the types and added some docs explaining the note and a brief comment on the function definition ✅

File: packages/hoppscotch-common/src/helpers/kernel/rest/response.ts (hunk 2 above)
Comment (CuriousCorrelation) [reply packages/hoppscotch-common/src/helpers/kernel/rest/response.ts]: Good suggestion! Have added it to the same commit 🫡
